categories:
  recaptcha: ~
  sf-register:
    label: 'Frontend user registration'

settings:
  evoweb.recaptcha.publicKey:
    default: '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI'
    type: string
    category: recaptcha
  evoweb.recaptcha.privateKey:
    default: '6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe'
    type: string
    category: recaptcha
  evoweb.recaptcha.invisiblePublicKey:
    default: ''
    type: string
    category: recaptcha
  evoweb.recaptcha.invisiblePrivateKey:
    default: ''
    type: string
    category: recaptcha
  evoweb.recaptcha.apiServer:
    default: 'https://www.google.com/recaptcha/api.js'
    type: string
    category: recaptcha
  evoweb.recaptcha.verifyServer:
    default: 'https://www.google.com/recaptcha/api/siteverify'
    type: string
    category: recaptcha
  evoweb.recaptcha.lang:
    default: ''
    type: string
    category: recaptcha
  evoweb.recaptcha.theme:
    default: 'light'
    type: string
    enum:
      light: 'light'
      dark: 'dark'
    category: recaptcha
  evoweb.recaptcha.robotMode:
    default: 0
    type: bool
    category: recaptcha
  evoweb.recaptcha.enforceCaptcha:
    default: 0
    type: bool
    category: recaptcha
  evoweb.recaptcha.threshold:
    default: 0.5
    type: number
    category: recaptcha
  evoweb.sf-register.captchaId:
    default: 'recaptcha'
    type: string
    category: sf-register
